---
title: "Interactive plot of raster data with a vector overlay"
output: html_document
---
This tutorial covers the concept and the coding of a function the creates a plot of a raster with a vector dataset as an overlay.

##Preperation
Loading libraries:
```{r, message=FALSE, warning=FALSE}
library(raster)
library(sp)
library(rgdal)
library(latticeExtra)
library(shiny)
```
Reading files:
```{r, message=FALSE, warning=FALSE, results='hide'}
raster <- raster("D:\\Studium (EnvGEo)\\Erstes_Semester\\Data_Management\\Datasets\\fogo_landsat_2014-11-24\\LC82100502014328LGN00_B3.tif")
vector <- readOGR("D:\\Studium (EnvGEo)\\Erstes_Semester\\Data_Management\\Datasets\\fogo_field_survey_2014\\data_2014_subset1.shp", layer = "data_2014_subset1")
```
##Function for plotting the map
```{r, echo=T}
custom_map <- function(raster, vector, v.attr, v.classes, v.color="Greens", grid_lines = 5){
 
   if (projection(raster) != projection(vector)) {
    vector <- spTransform(vector, CRS(projection(raster)))
  }
  
  min <- max(mean(getValues(raster)) - sd(getValues(raster)), 0)
  max <- mean(getValues(raster)) + sd(getValues(raster))
  
  breaks <- seq(min, max, length.out = 256)
  
  yat = seq(extent(raster)@ymin, 
            extent(raster)@ymax, length.out = grid_lines)
  xat = seq(extent(raster)@xmin, 
            extent(raster)@xmax, length.out = grid_lines)

  
  attr.vec <- vector@data[,which(names(vector)==v.attr)]
  
  v.breaks <- seq(min(attr.vec, na.rm = T), max(attr.vec, na.rm = T), length.out = v.classes)

  
    
  vector_classes <- cut(vector@data[,colnames(vector@data) == v.attr], v.breaks)
  vector_colors <- colorRampPalette(brewer.pal(6,v.color))(6)
  
  plt <- spplot(raster, col.regions = gray.colors(256), at = breaks,
                key = list(space = 'left', text = list(levels(vector_classes)), 
                           points = list(pch = 21, cex = 2, fill = vector_colors)),
                colorkey=list(space="right"),
                panel = function(...){
                  panel.levelplot(...)
                  panel.abline(h = yat, v = xat, col = "grey0", lwd = 0.8, lty = 3) 
                },
                scales = list(x = list(at = xat),
                              y = list(at = yat)))
  
  
  orl <- spplot(vector, zcol = v.attr, col.regions = vector_colors, 
                cuts = v.breaks)
  
  plt + as.layer(orl)
  
}
```

##Interactive Map
```{r, echo=F}
  inputPanel(
    selectInput(inputId = "attribute", label = "Vector attribute for classification:",
                choices = names(vector), selected = names(vector)[2]),
    
    sliderInput(inputId = "classes", label = "Number of classes:", min = 2,
                max = 10, value = 5, step = 1),

        
    selectInput(inputId = "color", label = "Color scheme for classifying the vector data:",
                choices = c("Reds", "Greens", "Blues"), selected = "Reds"),
    
    sliderInput(inputId = "grid_lines", label = "Number of grid lines:", min = 2,
                max = 20, value = 5, step = 1)
  )
  
  renderPlot(
    custom_map(raster = raster, vector = vector, v.attr = input$attribute, v.classes = input$classes, v.color=input$color, grid_lines = input$grid_lines)
  )
```

