---
title: "W12-1: Shiny map"
runtime: shiny
output: html_document
---


```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(raster)
library(sp)
library(rgdal)
library(latticeExtra)
```

```{r, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
#Rasterobjekt
band3 <- raster("C:/Users/Jannik/Dropbox/Marburg/Datamanagement/Projektordner/Datasets/GIS/fogo_landsat_2014-11-24/LC82100502014328LGN00_B3.tif")
#Vektorobjekt
surveydata <- readOGR("C:/Users/Jannik/Dropbox/Marburg/Datamanagement/Projektordner/Datasets/GIS/fogo_field_survey_2014/data_2014_subset1.shp", layer = "data_2014_subset1")
```


## Interaktive Karte von Fogo
```{r, echo=F}
mapplot <- function(raster, vectororigin, vectorclasses=6, gridticks=5, farbe="greens", survey.att){
  
  CRS_check <- as.character(crs(vectororigin)) == as.character(crs(raster))
  if (CRS_check == FALSE){
    vector <- spTransform(vectororigin, CRS(projection(raster)))
  }
  else{
    vector <- vectororigin
  }
  
  min <- max(mean(getValues(raster)) - sd(getValues(raster)), 0)
  max <- mean(getValues(raster)) + sd(getValues(raster))
  breaks <- seq(min, max, length.out = 256)
  
  yat = seq(extent(raster)@ymin, 
            extent(raster)@ymax, length.out = gridticks)
  xat = seq(extent(raster)@xmin, 
            extent(raster)@xmax, length.out = gridticks)
  
  vector.attribute <- na.omit(vector@data[,colnames(vector@data) == survey.att])
  
  vector_classes <- cut(vector.attribute, c(seq(0,max(vector.attribute), by=max(vector.attribute)/vectorclasses)))
  vector_colors <- colorRampPalette(brewer.pal(vectorclasses,farbe))(vectorclasses)
  
  plt <- spplot(raster, col.regions = gray.colors(256), at = breaks,
                key = list(space = 'left', text = list(levels(vector_classes)), 
                           points = list(pch = 21, cex = 2, fill = vector_colors)),
                colorkey=list(space="right"),
                panel = function(...){
                  panel.levelplot(...)
                  panel.abline(h = yat, v = xat, col = "grey0", lwd = 0.8, lty = 3) 
                },
                scales = list(x = list(at = xat),
                              y = list(at = yat)))
  
  orl <- spplot(vector, zcol = survey.att, col.regions = vector_colors, 
                cuts = c(seq(0,max(vector.attribute), by=max(vector.attribute)/vectorclasses)))
  
  plt + as.layer(orl)
}

```


```{r, echo=FALSE}
#Shiny Aufruf
inputPanel(
  selectInput("attribute", label = "Attribute", choices = names(surveydata), selected = "ID"),
  
  selectInput("color", label = "Farbpalette", 
              choices = c("Greens", "Reds", "Blues"), selected = "Greens"),
  
  sliderInput("gridtickadjust", label = "Number of ticks in grid:",
              min = 2, max = 12, value = 1, step = 1),
  
  sliderInput("classes", label = "Number of Classes", min = 2, max = 6, value = 1, step = 1)
  
)

renderPlot({
  #spplot(surveydata, z= input$attribute)
  #Aufrufen der Funktion
  mapplot(band3,surveydata, vectorclasses = input$classes, gridticks = input$gridtickadjust, farbe=input$color, survey.att = input$attribute)
})
```
